### PR TITLE
.github/workflows: fix wrong branch name

### PR DESCRIPTION
**Pull request by cuonglm**

### CODE REVIEW

**Comment by cuonglm** [comment]
cc @odeke-em

**Review by odeke-em — APPROVED** [review]
Thank you @cuonglm, LGTM!

**Comment by cuonglm** [comment]
@odeke-em Please merge when CI green, I don't have access to this repo 😄

**Comment by odeke-em** [comment]
> @odeke-em Please merge when CI green, I don't have access to this repo 😄 

My apologies. When I get to my computer I'll add you as an admin.

**Pull request merged**
