### PR TITLE
Add Github Action

### PR DESCRIPTION
**Pull request by cuonglm**

### CODE REVIEW

**Comment by cuonglm** [comment]
cc @odeke-em

**Review by odeke-em — APPROVED** [review]
LGTM, thank you @cuonglm!

**Comment by cuonglm** [comment]
@odeke-em Thanks for reviewing!

I don't have maintainer access to this repo, and also orijtech/otils, so please help me submitting these PRs.

**Comment by odeke-em** [comment]
> @odeke-em Thanks for reviewing!
> 
> 
> 
> I don't have maintainer access to this repo, and also orijtech/otils, so please help me submitting these PRs.

Sure, I'll do so when I get home and my computer.

**Pull request merged**
